#!/bin/bash

docker compose -f heap/docker-compose.yml down && \
  docker network prune -f && \
  docker compose -f heap/docker-compose.yml pull && \
  docker compose -f heap/docker-compose.yml up --build --attach passay-heap
