/* See LICENSE for licensing and NOTICE for copyright. */
package org.passay;

/**
 * Contains determines the origin of a given {@link PasswordData}
 *
 * @author  Middleware Services
 */
public final class PasswordOrigin
{

  /**
   * {@link PasswordOrigin} identifying a password which was generated by a typical human user.
   */
  public static final PasswordOrigin USER_GENERATED = new PasswordOrigin("USER_GENERATED");

  /**
   * {@link PasswordOrigin} identifying a password which was generated by a sufficient random source.
   */
  public static final PasswordOrigin RANDOM_GENERATED = new PasswordOrigin("RANDOM_GENERATED");

  /** *  Type code referencing this {@link PasswordOrigin} **/
  private final String type;


  /**
   * Private constructor, this class cannot be instantiated, it is intended for public access to its static members.
   *
   * @param t type
   */
  private PasswordOrigin(final String t)
  {
    this.type = t;
  }


  /**
   * Returns the type.
   *
   * @return  type
   */
  public String getType()
  {
    return type;
  }


  @Override
  public String toString()
  {
    return String.format("%s@%h::type=%s", getClass().getName(), hashCode(), type);
  }

}
