#!/bin/bash

function user_continue() {
  read -p "Do you want to continue? [y/n]" -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
}

if [ "$#" -ne 1 ]; then
  echo "USAGE: `basename $0` <repo-path>"
  exit
fi

REPO_PATH="${1}"
SHA=`git rev-parse --verify HEAD`
echo "================================================================="
echo "BEGIN PUBLISH SNAPSHOT for revision ${SHA} at ${REPO_PATH}"
echo "================================================================="
user_continue

# Build snapshot jars
if ! mvn -Pintegration,fuzz,heap,distribution clean; then
  echo "maven clean command failed, check your environment"
  exit
fi
mvn package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
COMPILE_VERSION=$(javap -classpath core/target/passay-${POM_VERSION}.jar -verbose org.passay.PasswordValidator |grep "major version:" |tr -d '[:space:]' |cut -d':' -f2)
echo "Class compile version is ${COMPILE_VERSION}"
if [ "${COMPILE_VERSION}" != "52" ]; then
  echo "Snapshot must be compiled for Java 8"
  exit
fi

# Pull latest from the maven repo
pushd ${REPO_PATH}
git pull
popd

# Deploy the artifact to the maven repo
mvn deploy -Dmaven.test.skip=true -Daether.checksums.algorithms=MD5,SHA-1,SHA-256,SHA-512 -Dsign=true -DaltDeploymentRepository=snapshot::file://${REPO_PATH}

# Push changes to the maven repo
pushd ${REPO_PATH}
git add .
git commit -a -m "Publish snapshot: ${SHA}"
git push origin master
popd

echo "Successfully published SNAPSHOT artifacts for ${SHA}"
