/* See LICENSE for licensing and NOTICE for copyright. */
package org.passay.support;

/**
 * Enum to define the origin of a password.
 *
 * @author  Middleware Services
 */
public enum Origin
{

  /** a password which was generated by a typical human user. */
  User,

  /** a password which was generated by a sufficient random source. */
  Generated
}
